//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutputInspectionResult.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutputInspectionResult.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   点検名,WSNo,点検日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CSV_Header {
            get {
                return ResourceManager.GetString("CSV_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ,画像解析結果（{0}）,NGコメント（{0}）,画像パス（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CSV_Header_AI {
            get {
                return ResourceManager.GetString("CSV_Header_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ,{0}（品番）,{0}（編集済品番）,{0}（製造番号）,{0}（編集済製造番号）,画像パス（{0}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CSV_Header_OCR {
            get {
                return ResourceManager.GetString("CSV_Header_OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムエラーが発生しました。システム管理者に確認してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_001 {
            get {
                return ResourceManager.GetString("E_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点検日の開始日は終了日以前の日付となるように入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_002 {
            get {
                return ResourceManager.GetString("E_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   必須項目が含まれていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_003 {
            get {
                return ResourceManager.GetString("E_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータの型に誤りがあります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_004 {
            get {
                return ResourceManager.GetString("E_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB接続でエラーが発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_005 {
            get {
                return ResourceManager.GetString("E_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期せぬエラーが発生しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_006 {
            get {
                return ResourceManager.GetString("E_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点検名を選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_007 {
            get {
                return ResourceManager.GetString("E_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S3接続でエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_008 {
            get {
                return ResourceManager.GetString("E_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定パラメータ以外のパラメータが存在します に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_009 {
            get {
                return ResourceManager.GetString("E_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点検日の開始から終了までは{0}日未満となるように入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string E_010 {
            get {
                return ResourceManager.GetString("E_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点検結果出力が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_001 {
            get {
                return ResourceManager.GetString("M_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点検結果出力を中止しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_002 {
            get {
                return ResourceManager.GetString("M_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_003 {
            get {
                return ResourceManager.GetString("M_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件に該当するデータがありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_004 {
            get {
                return ResourceManager.GetString("M_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点検名データがありませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_005 {
            get {
                return ResourceManager.GetString("M_005", resourceCulture);
            }
        }
    }
}
