# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'OnSiteInspection' do
  use_frameworks!
  pod 'APIKit'
  pod 'R.swift'
  pod 'RealmSwift'
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'XCGLogger'
  pod 'NVActivityIndicatorView'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
